version: "3.8"

services:
  redis-app-isca:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - isca-network

  django-app-isca:
    image: jrrychen/isca-django
    container_name: django-app-isca
    build:
      context: ./isca_swim_scorer
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./isca_swim_scorer:/usr/src/app
      - media_volume:/usr/src/app/media
    ports:
      - "80:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,100.27.220.135,4.246.206.246,scorer.swimisca.org,swimisca.org,www.swimisca.org,*
      - SECRET_KEY=1243546547365
      - X_FRAME_OPTIONS=SAMEORIGIN
      - CSRF_TRUSTED_ORIGINS=https://4.246.206.246,https://scorer.swimisca.org,https://swimisca.org,https://www.swimisca.org
    depends_on:
      - redis-app-isca
    restart: unless-stopped
    networks:
      - isca-network

  celery-app-isca:
    image: jrrychen/isca-celery
    container_name: celery-app-isca
    build:
      context: ./isca_swim_scorer
    command: celery --app=isca_swim_scorer worker --loglevel=info
    volumes:
      - ./isca_swim_scorer:/usr/src/app
      - media_volume:/usr/src/app/media
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1,100.27.220.135,4.246.206.246,scorer.swimisca.org,swimisca.org,www.swimisca.org,*
      - SECRET_KEY=1243546547365
    depends_on:
      - redis-app-isca
      - django-app-isca
    restart: unless-stopped
    networks:
      - isca-network

networks:
  isca-network:
    driver: bridge

volumes:
  redis_data:
  media_volume:
