version: "3.8"

services:
  redis-app-isca:
    image: redis

  django-app-isca:
    container_name: django-app-isca
    build:
      context: ./isca_swim_scorer
    volumes:
      - ./isca_swim_scorer:/usr/src/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=1243546547365
    depends_on:
      - redis-app-isca

  celery-app-isca:
    container_name: celery-app-isca
    build:
      context: ./isca_swim_scorer
    volumes:
      - ./isca_swim_scorer:/usr/src/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - SECRET_KEY=1243546547365
    depends_on:
      - redis-app-isca
