version: "3.8"

services:
  redis-app-isca:
    image: redis:latest
    container_name: isca-redis-prod
    restart: unless-stopped
    volumes:
      - redis_data:/data

  django-app-isca:
    image: jrrychen/isca-django
    container_name: isca-django-prod
    command: gunicorn isca_swim_scorer.wsgi:application --bind 0.0.0.0:8000 --workers 2 --timeout 120
    volumes:
      - ./isca_swim_scorer:/usr/src/app
      - media_volume:/usr/src/app/media
    ports:
      - "80:8000"
      - "443:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,ISCA.red,www.ISCA.red
      - SECRET_KEY=1231251231421
      - X_FRAME_OPTIONS=SAMEORIGIN
      - CSRF_TRUSTED_ORIGINS=https://ISCA.red,https://www.ISCA.red
    depends_on:
      - redis-app-isca
    restart: unless-stopped

  celery-app-isca:
    image: jrrychen/isca-celery
    container_name: isca-celery-prod
    command: celery --app=isca_swim_scorer worker --loglevel=info
    volumes:
      - ./isca_swim_scorer:/usr/src/app
      - media_volume:/usr/src/app/media
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,ISCA.red,www.ISCA.red
      - SECRET_KEY=1231251231421
    depends_on:
      - redis-app-isca
      - django-app-isca
    restart: unless-stopped

volumes:
  redis_data:
  media_volume:
