version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=isca_swim_scorer.settings
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
