# Generated by Django 5.2 on 2025-05-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.CharField(choices=[('SCY', 'Short Course Yards'), ('LCM', 'Long Course Meters'), ('SCM', 'Short Course Meters')], default='SCY', max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_errors', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('stroke', models.CharField(choices=[('FR', 'Freestyle'), ('BK', 'Backstroke'), ('BR', 'Breaststroke'), ('FL', 'Butterfly'), ('IM', 'Individual Medley'), ('MR', 'Medley Relay'), ('FRR', 'Freestyle Relay')], max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed'), ('U', 'Unknown')], max_length=1)),
                ('is_relay', models.BooleanField(default=False)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meets.meet')),
            ],
            options={
                'ordering': ['event_number'],
                'unique_together': {('meet', 'event_number')},
            },
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mixed'), ('U', 'Unknown')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('swimmer_meet_id', models.CharField(blank=True, max_length=20)),
                ('usa_swimming_id', models.CharField(blank=True, max_length=20)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='meets.meet')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed_time', models.FloatField(blank=True, null=True)),
                ('prelim_time', models.FloatField(blank=True, null=True)),
                ('swim_off_time', models.FloatField(blank=True, null=True)),
                ('final_time', models.FloatField(blank=True, null=True)),
                ('prelim_place', models.IntegerField(blank=True, null=True)),
                ('swim_off_place', models.IntegerField(blank=True, null=True)),
                ('final_place', models.IntegerField(blank=True, null=True)),
                ('prelim_points', models.FloatField(default=0)),
                ('swim_off_points', models.FloatField(default=0)),
                ('final_points', models.FloatField(default=0)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('is_exhibition', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='meets.event')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='meets.swimmer')),
            ],
            options={
                'ordering': ['event', 'final_place', 'prelim_place', 'swim_off_place'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='meets.meet')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('code', 'meet')},
            },
        ),
        migrations.AddField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='meets.team'),
        ),
        migrations.AlterUniqueTogether(
            name='swimmer',
            unique_together={('swimmer_meet_id', 'meet')},
        ),
    ]
