# Generated by Django 4.2.10 on 2025-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_result_best_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stroke',
            field=models.CharField(choices=[('FR', 'Freestyle'), ('BK', 'Backstroke'), ('BR', 'Breaststroke'), ('FL', 'Butterfly'), ('IM', 'Individual Medley'), ('MR', 'Medley Relay'), ('FRR', 'Freestyle Relay'), ('OTH', 'Other/Dryland')], max_length=255),
        ),
    ]
