# Generated by Django 5.2 on 2025-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('HY3', 'HY3 - Meet Manager Export'), ('ZIP', 'ZIP - Compressed File (must contain HY3)')], max_length=6),
        ),
    ]
