# Generated by Django 4.2.10 on 2025-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('HY3', 'HY3 - Meet Manager Export'), ('ZIP', 'ZIP - Compressed Folder containing HY3 file'), ('XLSX', 'XLSX - Dryland Events Template')], max_length=6),
        ),
    ]
