# Generated by Django 5.2 on 2025-05-07 20:44

import django.db.models.deletion
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=uploads.models.upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('HY3', 'HY3 - Meet Manager Export'), ('CL2', 'CL2 - Results Export'), ('ZIP', 'ZIP - Compressed File'), ('OTHER', 'Other File Type')], max_length=6)),
                ('source_type', models.CharField(choices=[('WEB', 'Web Upload'), ('EMAIL', 'Email Upload'), ('API', 'API Upload'), ('OTHER', 'Other Source')], default='WEB', max_length=6)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_errors', models.TextField(blank=True)),
                ('meet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='meets.meet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
