# Generated by Django 4.2.10 on 2025-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
