# Generated by Django 4.2.10 on 2025-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_uploadedfile_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('HY3', 'HY3 - Meet Manager Export')], max_length=6),
        ),
    ]
