# Generated by Django 4.2.10 on 2025-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('HY3', 'HY3 - Meet Manager Export'), ('ZIP', 'ZIP - Compressed HY3 File')], max_length=6),
        ),
    ]
